<a href="https://colab.research.google.com/github/NoorNabi50/-Deep-Learning-und-Textanalyse-in-Finance-Exercises/blob/main/Deep_Learning_and_Textanalyse_in_Finance_Tutorial_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

A = np.array([[1,2,3],[4,5,6],[7,8,9]])

B = np.array([[2,4,6,8],[1,3,5,7],[9,11,13,15]])

C = np.array([[1,0,2,4,6],[3,5,7,9,11]])

D = np.array([[1,3,5,7],[2,4,6,8],[9,11,13,15],[10,12,14,16]])

At = np.transpose(A)
Bt = np.transpose(B)
Ct = np.transpose(C)
Dt = np.transpose(D)
#Task 1: Transpose matrices A, B, C, D

#print(At)
#print(Bt)
#print(Ct)
#print(Dt)

#Task 2a:
#print(np.dot(A,A.T))

#Task 2b:

#print(np.dot(A,B.T))

#Task 2c
#print(np.dot(At,B))

#Task 2d:
#print(np.dot(B,Dt))

#Task 2e:
#print(np.dot(Bt,A))

#Task 2f:
#print(np.dot(Bt,At))

#Task 2g:
#print(np.dot(C,Ct))

#Task 2h:
print(np.dot(Ct,C))

[[ 10  15  23  31  39]
 [ 15  25  35  45  55]
 [ 23  35  53  71  89]
 [ 31  45  71  97 123]
 [ 39  55  89 123 157]]
